[package]
name = "acr-cleaner"
version = "0.1.0"
authors = ["bc ko <gobcko@gmail.com>"]
edition = "2018"

[dependencies]

serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
chrono = { version = "0.4.6", features = ["serde"] }
time = "0.1.40"
